language: objective-c
osx_image: xcode9.2
env:
  global: 
script:
- xcodebuild -version
- xcodebuild -showsdks
- fastlane build
notifications:
  slack:
    secure: WBEUqnwgGAoA0otgf04JGuB0ft4J/cmAb5jh7VA0oCFWTWxHer3dq1J9nS/A1vEy86qogNaCEav1RmFklb7M+NtGTkuZ4btxAEdXqoGwuBJORrAUIx2YZee62B1T4DSdQusPQzy38Q0Ta618BG1ZMnr1hFdspMIPDXaOyGjS8x6EYyMiTyRCAhCEOFQFr+nSnxm/+dRPSqtUc8AhnnudAQaokA6WvcGtxGPljFmYqWzqYQYlaLAOwsIIO8E0Zob9s0mrFPZmklBJAqgtpzVZsvv6C+stp/UokAfZP2I3KoXAJkCvqI4nniykc3t6Q9CQs0Y5t+DOYTL2XDj+SgQNLbysLE/kbTUhW3LeSvH29qQn2wXrqh8WebmotZKO62Ls0DE+izdisiQ4gBEgDs3sKdeuIzdHZkFdBFsC+LHp8mKDzHoNNAq2fyot5yYvCc31F8OPdMaVtFYciCsuvUnWz1tLsv0p/S8VITJIwle8rPFCCDw+LgunuSJfv0iBwmVilvJMd50zdNNprh5ZIojgCbgjqMSbG0SJUXy32+vM//5gnsGZrJy4TJmMDLvi7i5w2IVtWNpVN3DRsNjFCynBR3RXpizFUfvMsqIuNK7XSbJEEvTuIkxbaDN+9rrHM1FcWs5CsJuD+vk+4pGjNx6xgrBzeQ3Va09IaFSXvqsaNNE=
